name: Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: ["main"] # Se déclenche quand tu pushes sur main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /blabla
            git fetch origin
            git checkout main
            git pull origin main
            echo "Déploiement terminé !"
