name: Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: ["main"] # Se déclenche quand tu pushes sur main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            if [ -d "/reseau-social-quelconque" ]; then
              cd /reseau-social-quelconque
              git fetch origin
              git checkout main
              git pull origin main
            else
              echo "Repository not on VPS ! Cloning...."
              git clone git@github.com/Karssou/reseau-social-quelconque.git
              touch test.txt
            fi
            echo "Déploiement terminé !"
