name: Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: ["main"] # Se déclenche quand tu pushes sur main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Couleurs pour les messages
            RED='\033[0;31m'
            GREEN='\033[0;32m'
            YELLOW='\033[1;33m'
            NC='\033[0m' # No Color

            # Chemin du dépôt
            REPO_PATH="reseau-social-quelconque"
            REPO_URL="git@github.com:Karssou/reseau-social-quelconque.git"

            echo -e "${YELLOW}=== Début du déploiement ===${NC}"

            if [ -d "$REPO_PATH" ]; then
              echo -e "${GREEN}✅ Dépôt trouvé. Mise à jour en cours...${NC}"
              cd "$REPO_PATH" || { echo -e "${RED}❌ Erreur : Impossible d'entrer dans $REPO_PATH${NC}"; exit 1; }

              echo -e "${YELLOW}→ Récupération des dernières modifications...${NC}"
              git fetch origin || { echo -e "${RED}❌ Erreur lors du fetch${NC}"; exit 1; }

              echo -e "${YELLOW}→ Bascule sur la branche main...${NC}"
              git checkout main || { echo -e "${RED}❌ Erreur lors du checkout${NC}"; exit 1; }

              echo -e "${YELLOW}→ Mise à jour du code...${NC}"
              git pull origin main || { echo -e "${RED}❌ Erreur lors du pull${NC}"; exit 1; }

              echo -e "${GREEN}✅ Code mis à jour avec succès !${NC}"
            else
              echo -e "${YELLOW}⚠️  Dépôt non trouvé. Clonage en cours...${NC}"

              git clone "$REPO_URL" || { echo -e "${RED}❌ Erreur lors du clone${NC}"; exit 1; }
              echo -e "${GREEN}✅ Dépôt cloné avec succès !${NC}"

              # Optionnel : Créer un fichier de test (exemple)
              touch "$REPO_PATH/test.txt" && echo -e "${GREEN}✅ Fichier de test créé.${NC}"
            fi

            # Vérification finale
            if [ -d "$REPO_PATH" ]; then
              echo -e "${GREEN}============================${NC}"
              echo -e "${GREEN}✨ Déploiement terminé avec succès ! ✨${NC}"
              echo -e "${GREEN}============================${NC}"
            else
              echo -e "${RED}❌ ÉCHEC : Le dépôt n'a pas été déployé.${NC}"
              exit 1
            fi
